## **Principal Component Analysis**

In [1]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [25]:
X = np.array([
    [2,4],
    [3,6],
    [4,8],
    [5,10]
])

print("Original Data:\n", X)

Original Data:
 [[ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]]


In [26]:
X_centered = X - np.mean(X, axis=0)
print("Mean Centered Data:\n", X_centered)

Mean Centered Data:
 [[-1.5 -3. ]
 [-0.5 -1. ]
 [ 0.5  1. ]
 [ 1.5  3. ]]


In [27]:
cov_matrix = np.cov(X_centered.T)
print("Covariance Matrix:\n", cov_matrix)

Covariance Matrix:
 [[1.66666667 3.33333333]
 [3.33333333 6.66666667]]


In [30]:
eig_vals, eig_vecs = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n", eig_vals)
print("Eigenvectors:\n", eig_vecs)

explained_variance_ratio = eig_vals / np.sum(eig_vals)
print("Explained Variance Ratio:\n", explained_variance_ratio)

Eigenvalues:
 [0.         8.33333333]
Eigenvectors:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
Explained Variance Ratio:
 [0. 1.]


In [29]:
X_pca = np.dot(X_centered, eig_vecs)

print("PC1 and PC2 values:\n", X_pca)

PC1 and PC2 values:
 [[ 5.55111512e-17  3.35410197e+00]
 [ 0.00000000e+00  1.11803399e+00]
 [ 0.00000000e+00 -1.11803399e+00]
 [-5.55111512e-17 -3.35410197e+00]]
